# Generated by Django 4.0.6 on 2022-12-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_post_created_at_post_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
