# Generated by Django 4.0.6 on 2022-12-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_post_updated_alter_post_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.CharField(default='', max_length=10),
        ),
    ]
